### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by diasdavid** [ipfs-shipyard/shipyard#1]
@akrych mind adding the logo in .svg and multiple exports such as https://github.com/ipfs/logo to this repo in a folder called logo?

**Comment by akrych** [comment]
Hello @diasdavid, 

Want to upload files but I think I don't have permission to do this :) 
Can you do this? They are here: https://drive.google.com/drive/u/1/folders/1htEeb3AaAETs5liNGnDOT1ZfC7SX2Zs2

**Comment by diasdavid** [comment]
Added, thank you @akrych :) https://github.com/ipfs-shipyard/shipyard/commit/6ea02231fd6822883fc46acc6330d23b28e5fb35
